### ISSUE TITLE
🐛 [BUG] Fix Dependabot Alerts

### ISSUE THREAD

**Issue by MidouWebDev** [Heptagram-Bot-Project/website#103]
### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by Panquesito7** [comment]
We could run `npm fix audit --force` (or something similar to that) to fix some of them, but there could be problems, AFAIK.

**Comment by MidouWebDev** [comment]
I still get this even if i downloaded the latest version :
BUG : https://github.com/Heptagram-Bot/heptagram.xyz/security/dependabot/package-lock.json/ansi-html/open

@j-dogcoder

**Comment by Panquesito7** [comment]
> I still get this even if i downloaded the latest version : BUG : https://github.com/Heptagram-Bot/heptagram.xyz/security/dependabot/package-lock.json/ansi-html/open
> 
> Can we dismiss it ?
> 
> @j-dogcoder

Not sure if it's a good idea to dismiss it. We should keep it there and try to fix it (in the future).

**Comment by j-dogcoder** [comment]
I agree with @Panquesito7
