### ISSUE TITLE
✨❓ Feature Request: Upgrade React Router to v6

### ISSUE THREAD

**Issue by MidouWebDev** [Heptagram-Bot-Project/website#104]
**Description**

React Router has now the v6, we should update !
More informations [here](https://reactrouter.com/docs/en/v6/upgrading/v5)

**Comment by j-dogcoder** [comment]
Hey @MidouWebDev, any update?

**Comment by MidouWebDev** [comment]
@j-dogcoder there are some bugs in the app.js file related to routing that's why we can't see the other pages and it is due to react routing bug.
Currently, i have an issue with my laptop so i can't work on it.

**Comment by Sam-Radnus** [comment]
@MidouWebDev can i work on it

**Comment by MidouWebDev** [comment]
> @MidouWebDev can i work on it

Sure ! 
So we need to upgrade the routing system so as to navigate between the website pages.
As you can see in the website, once we click on a page link we see an error. I hope it is going to be fixed

Thanks a lot !
