### ISSUE TITLE
✨❓ Dashboard Feature : **FREE** Bot Commands List

### ISSUE THREAD

**Issue by MidouWebDev** [Heptagram-Bot-Project/website#90]
**Description**

@j-dogcoder 
We need a list of the **FREE** customisable bot commands that Heptagram offers.

**Comment by j-dogcoder** [comment]
Currently that is all of them.

**Comment by MidouWebDev** [comment]
Sorry @j-dogcoder, i don't get the point.
Would you clarify that, please ?
Thanks
