### ISSUE TITLE
🐛 [BUG] Website not working !

### ISSUE THREAD

**Issue by MidouWebDev** [Heptagram-Bot-Project/website#95]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

![Screenshot_20211102-202722_Samsung Internet](https://user-images.githubusercontent.com/72341453/139936649-67f1ccaf-eaaf-4351-8ec0-a32bd810c7ef.jpg)

### Anything else?

@j-dogcoder 

Priority : **CRITICAL**

**Comment by j-dogcoder** [comment]
Yeah, because I haven't put the react js version up yet

**Comment by MidouWebDev** [comment]
👍🏼

**Comment by j-dogcoder** [comment]
Working.
